server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/securityjwt?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'theJwtSecretKey'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
    user:
      name: bobby
      password: 123456
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'


# 日志配置
logging:
  level:
    com.bobby: debug


# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml # mapper.xml扫描地址

